
#define DUNE_PDU_VERSION 1
#define DUNE_PDU_DATA_LENGTH 4096
//#define DUNE_PDU_SIZE sizeof(dune::Net::IO::DUNE_PDU)
#define DUNE_NET_DIFFICULTY 10
#define DUNE_NET_PORT 2323
#define DUNE_COMMUNITY_STRING "124"
#define DUNE_MAX_CONNECTIONS 25
#define DUNE_CRYPTO_MAX_DIFFICULTY_POW 24